name: Build Nginx/Docker Image

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  repository_dispatch:
    types: [docker]
  workflow_dispatch:
    inputs:
      Force_update:
        description: "强制更新"
        type: boolean
        default: false
        required: false
  push:
    branches:
      - "main"
      - "latest"
      - "releases/**"
    tags:
      - v*
    paths:
      - "**/*docker*"
      - "**/*py*"
      - "**/*sh*"
      - Dockerfile
      - .github/workflows/nginx-docker.yml


  schedule:
    - cron: "10 11 * * 6"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nginx-quic

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "${{ github.actor }}/nginx-quic"

      - name: Init
        run: |
          full_image_name="${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}"
          echo "full_image_name=$full_image_name" >>"$GITHUB_ENV"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.full_image_name }}

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login To DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert Username
        id: un
        run: echo "un=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build & Push Multiarch Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ghcr.io/${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "BUILD=${{ github.event.repository.name }}"

      - name: TG_Bot推送
        if: failure()
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_CHAT_ID: ${{ secrets.TG_USER_CHAT_ID }}
        run: |
          MESSAGE="Error:${GITHUB_WORKFLOW}-${GITHUB_JOB}-${GITHUB_RUN_NUMBER}"
          $GITHUB_WORKSPACE/scripts/tg_bot_message.sh "$MESSAGE"
